apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  serviceAccountName: test
  containers:
  - name: command-demo-container
    image: mariojacobo/kubectl:v1
    command: ["/bin/sh","-c"]
    args: ["kubectl get pods"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: test
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
#automountServiceAccountToken: false
